name: Build APK

on:
  push:
    branches:
      - master  # 或者 master，根据你项目的主分支名称来选择
  pull_request:
    branches:
      - master  # 或者 master

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 环境
    
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 JDK 环境（默认 Android 项目需要 JDK 8 或更高版本）
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # 设置 Android SDK 环境
      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-action@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          # AVD 的名称
          avd-name: "Pixel_3a_API_30"

      # 构建 APK 使用 Gradle
      - name: Build APK with Gradle
        run: ./gradlew assembleRelease  # 如果你想构建 Release 版本的 APK
        # 或者: run: ./gradlew assembleDebug  # 如果你想构建 Debug 版本的 APK

      # 上传构建好的 APK 到 GitHub Releases（可选）
      - name: Upload APK to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/release/app-release.apk  # APK 路径，基于你的项目结构
