name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d temp
          mv temp/cmdline-tools $HOME/android-sdk/cmdline-tools
          
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/bin" >> $GITHUB_PATH
          
          yes | sdkmanager --sdk_root=$ANDROID_HOME \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "platform-tools"
          yes | sdkmanager --licenses

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease
        env:
          ANDROID_HOME: ${{ env.HOME }}/android-sdk

      - name: Upload APK
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          files: app/build/outputs/apk/**/*.apk
