name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 升级到最新 checkout 版本

      - name: Set up JDK 17  # 推荐使用较新 JDK 版本
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d $HOME/android-sdk/cmdline-tools/latest
          
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH
          
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platforms;android-33" \
            "build-tools;34.0.0" \
            "platform-tools" \
            "cmdline-tools;latest"

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease
        env:
          ORG_GRADLE_PROJECT_android.useAndroidX: true  # 确保启用 AndroidX

      - name: Upload APK
        uses: softprops/action-gh-release@v1  # 更活跃的 release action
        if: github.ref == 'refs/heads/master'  # 仅 master 分支触发上传
        with:
          files: app/build/outputs/apk/**/*.apk  # 通配符匹配所有 APK
